<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Aheadworks\Wbtab\Block\Wbtab\ProductList $block */
$items = $block->getItems();
if (count($items) > 0):
    $class = 'aw_wbtab';
    $image = 'related_products_list';

    $title = $block->getBlockTitle();
    $showCart =  $block->getDisplayAddToCart();
    $dataMageInit = $block->getDataMageInit();
?>

    <div data-mage-init='<?php /* @noEscape */ echo $dataMageInit ?>' class="block <?php /* @noEscape */ echo $class; ?>" >
        <div class="block-title title">
            <strong id="block-<?php /* @noEscape */ echo $class?>-heading" role="heading" aria-level="2"><?php echo $block->escapeHtml($title); ?></strong>
        </div>
        <div class="block-content content" aria-labelledby="block-<?php /* @noEscape */ echo $class?>-heading">
            <div class="products wrapper grid products-grid products-<?php /* @noEscape */ echo $class; ?>">
                <ol data-aw-wbtab-block="items" class="products list items product-items">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php $available = ''; ?>

                        <?php if (!$_item->isComposite() && $_item->isSaleable()): ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php /* @noEscape */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>

                        <div class="product-item-info <?php /* @noEscape */ echo $available; ?>">
                            <?php /* @noEscape */ echo '<!-- ' . $image . '-->' ?>
                            <a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                        <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                </strong>

                                <?php /* @noEscape */ echo $block->getProductPrice($_item); ?>
                                <?php if ($showCart): ?>
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()): ?>
                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @noEscape */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php echo $block->escapeHtml(__('Add to Cart')) ?>">
                                                            <span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            <?php else: ?>
                                                <?php
                                                $postData = $block->getPostDataHelper()
                                                    ->getPostData(
                                                        $block->getAddToCartUrl($_item),
                                                        ['product' => $_item->getEntityId()]
                                                    );
                                                ?>

                                                <button class="action tocart primary"
                                                        data-post='<?php /* @noEscape */ echo $postData; ?>'
                                                        type="button" title="<?php echo $block->escapeHtml(__('Add to Cart')) ?>">
                                                    <span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            <?php endif; ?>
                                        <?php else: ?>
                                            <?php if ($_item->getIsSalable()): ?>
                                                <div class="stock available"><span><?php echo $block->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>

<?php endif;?>
